### ISSUE TITLE
Decode error response?

### ISSUE THREAD

**Issue by kevinrenskers** [gonzalezreal/SimpleNetworking#8]
Is there an easy way to decode the response in case of an error? For example when the response' status code is 401, I know there will a challenge object in the response, which I need to re-authenticate the user (using 2FA). 

APIClient throws a BadStatusError which contains the data, so I can decode that manually (inside a tryCatch operator?) but it doesn't seem ideal. Wondering if the library can make this easier?

**Comment by gonzalezreal** [comment]
At the moment that functionality is not covered.

A nice way of supporting this would be to encode the error type in `Endpoint`, together with the output type.

Any suggestions or help is welcome 😄
